apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-deployment-v2
  labels:
    app: {{ .Values.appName }}
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      version: v2
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        version: v2
    spec:
      containers:
      - name: apache
        image: httpd:2.4
        ports:
        - containerPort: 80
