apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-v2
  labels:
    app: {{ .Values.deployment.v2Name }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.deployment.podName }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.podName }}
    spec:
      containers:
      - name: apache
        image: httpd:2.4
        ports:
        - containerPort: 80
