apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-v2
  labels:
    app: {{ .Values.deployment.v2Name }}
    version: v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.deployment.podName }}
      version: v2
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.podName }}
        version: v2
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: type
                  operator: In
                  values:
                  - compute
      containers:
      - name: apache
        image: httpd:2.4
        ports:
        - containerPort: 80
