apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-v1
  labels:
    name: webserver
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      name: webserver
      version: v1
  template:
    metadata:
      labels:
        name: webserver
        version: v1
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: type
                  operator: In
                  values:
                  - compute
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
      
