apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-v1
  labels:
    app: {{ .Values.deployment.v1Name }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.deployment.podName }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.podName }}
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
