apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-v2
  labels:
    name: webserver
    version: v2
spec:
  replicas: 2
  selector:
    matchLabels:
      name: webserver
      version: v2
  template:
    metadata:
      labels:
        name: webserver
        version: v2
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: type
                  operator: In
                  values:
                  - compute
      containers:
      - name: apache
        image: httpd:2.4
        ports:
        - containerPort: 80
