apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-deployment-v1
  labels:
    app: {{ .Values.appName }}
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      version: v1
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        version: v1
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
      
