kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Values.deployment.podName }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
  type: {{ .Values.service.srvType }}

