kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    app: {{ .Values.deployment.podName }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: {{ .Values.service.srvType }}

