kind: Service
apiVersion: v1
metadata:
  name: webserver
  labels:
    name: webserver
spec:
  selector:
    name: webserver
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: {{ .Values.service.srvType }}

