kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.appName }}-srv
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: {{ .Values.service.srvType }}

